### ISSUE TITLE
Add point about performance to "What is Bonsai?" article

### ISSUE THREAD

**Issue by taunsquared** [bonsai-rx/docs#27]

**Comment by banchan86** [comment]
Not sure what was supposed to be added here (minimum hardware requirements?) but given the wide range of applications it might be hard to make a blanket point about performance. It might be worthwhile to maybe add a section on validating workflows though in the "Workflow Guidelines" article or a separate article under "Guidelines" (checking video frame timestamps for example). I will make a separate issue for that, closing this for now.
