### ISSUE TITLE
Add a small page with explanation on reorder connection

### ISSUE THREAD

**Issue by orena1** [bonsai-rx/docs#31]
Might be good to add a small page on the concept of reorder connection, why is it important, and when it can be or can not be done.
![reorder_connection](https://user-images.githubusercontent.com/8983713/161456978-3f436f78-be32-4048-bb59-32ddfc62cfe8.gif)

See here: 
https://groups.google.com/g/bonsai-users/c/IvbLVrUC7X0

**Comment by glopesdev** [comment]
We will cover this in the workflow design guidelines #60.
