### ISSUE TITLE
Naming Csv Files with FileName Externalized Property

### ISSUE THREAD

**Issue by orena1** [bonsai-rx/docs#32]
Changing the name of a csv file as a function of variables is something any experimental will need to do, there is a small discussion about it here:
https://groups.google.com/g/bonsai-users/c/lEj2W_5qgfQ/m/M_hXa_OkAAAJ
https://discord.com/channels/722881880122327101/825109229735510066/946372302881308713
It will be good to add a page talking about it, maybe linked from a page talking about csvwrite etc..
I can try to create something,
Thanks

**Comment by glopesdev** [comment]
The general pattern for initializing filenames and properties is a great topic to include in the workflow design guidelines, which we will be working on soon #60.
