### ISSUE TITLE
Rename the repo

### ISSUE THREAD

**Issue by jonnew** [bonsai-rx/docs#5]
I dont have much room to say this since Open Ephys has a repo named "GUI", but IMO is a bit mean to force people to end up with forks like this in their github account
![image](https://user-images.githubusercontent.com/1429475/154096732-a61a25ca-3e36-4b64-923c-88fa9e467801.png)

**Comment by glopesdev** [comment]
I had the impression that you could just rename your local fork to be whatever you want and GitHub would still point to the correct root. Can you check if that still works?

Would be nice to keep the docs name for URL generation purposes.

**Comment by jonnew** [comment]
You are correct!
