### ISSUE TITLE
Workflow design guidelines

### ISSUE THREAD

**Issue by glopesdev** [bonsai-rx/docs#60]
A number of guidelines, patterns and motifs have emerged over the years of developing and using the language which would be useful to capture as part of the documentation. The goal is to avoid common pitfalls, share best practices and promote awareness about the internals of the compiler, language and reactive framework across the community.

Below is a non-exhaustive list:
- Variable declaration
- Group organization
- Property assignment
- Branch execution and initialization
- Operator argument order

**Comment by bruno-f-cruz** [comment]
### Higher Order operators
- Shared properties across instances of the same operator and how to get around it
- The 'Concat' race condition when starting an observable as a case study/example of initialization
- SelectMany + Take in State machines

### Pipeline bottlenecks 
- What can happen (.e.g dropped frames, memory accumulation etc...)
- How to solve them? (e.g. ObserveOn)

### Timer(rx) vs Timer(gl) and other schedulers

### Hardware initialization motifs
- Using subjects to initialize hardware operators and subscribe downstream;
- The Harp initialization motif;
- Use hardware "create" nodes when available;

**Comment by aspaNeuro** [comment]
Keep all Hardware in high level workflows.
Shared variables declarations
Separate visualization from behavior



__
André Almeida
Tel: +44 (0) 77 3736 2319
Email: ***@***.******@***.***>
Website: https://neurogears.org<https://neurogears.org/>
Address: 31 Oval Road, London, NW1 7EA

NeuroGEARS Ltd is a limited company registered in England and Wales.
Company Registration No. 10773335
